# ch5. ndarray 연산
numpy ndarray도 더하고 빼기 연산을 할 수 있습니다.

### ndarray와 숫자 (스칼라값) 간의 연산
ndarray는 숫자와 더하기, 빼기, 나누기, 곱하기가 가능합니다. 이 때, ndarray의 모든 요소들에 해당 숫자 연산이 적용됩니다.

In [27]:
import numpy as np

In [30]:
a = np.arange(1, 9, 1).reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
a + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [32]:
a - 1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
a * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [34]:
a / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [35]:
a % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0]])

In [36]:
a // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4]])

### ndarray 간 연산
차원이 동일한 ndarray 간에는 사칙 연산이 가능합니다. 이 때는 ndarray의 동일한 인덱스끼리 연산을 수행합니다.

In [37]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
b = np.arange(9, 17, 1).reshape([2, 4])
b

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
a + b

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [40]:
a - b

array([[-8, -8, -8, -8],
       [-8, -8, -8, -8]])

In [41]:
a * b

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [ ]:
a / b

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.38461538, 0.42857143, 0.46666667, 0.5       ]])

In [46]:
b % a

array([[0, 0, 2, 0],
       [3, 2, 1, 0]])

In [47]:
b // a

array([[9, 5, 3, 3],
       [2, 2, 2, 2]])

### numpy boolean 연산
ndarray에 부등식 연산을 수행하면 각 원소에 대해서 부등식을 만족하는지 여부를 boolean 값으로 채워준 ndarray를 리턴합니다.

In [64]:
a = np.arange(1, 9, 1).reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
a > 4

array([[False, False, False, False],
       [ True,  True,  True,  True]])

이렇게 구한 boolean 값으로 채워진 ndarray는 인덱스처럼 사용할 수 있습니다.

In [66]:
a[a>4]

array([5, 6, 7, 8])

혹은 np.where를 사용하면 True인 값의 인덱스를 구할 수 있습니다.

In [68]:
np.where(a>4)

(array([1, 1, 1, 1]), array([0, 1, 2, 3]))

np.where를 통해 구한 값을 다시 인덱스로 사용할 수도 있다.

In [69]:
a[np.where(a>4)]

array([5, 6, 7, 8])

## 연습문제

ndarray 연산을 이용해서 아래와 같은 출력을 구해보세요.

In [9]:
import numpy as np

a = np.arange(1, 19, 2).reshape([3,3])
b = np.arange(2, 20, 2).reshape([3,3])
a, b

(array([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]]))

In [10]:
a + b

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [11]:
a - b

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [13]:
2*a + b

array([[ 4, 10, 16],
       [22, 28, 34],
       [40, 46, 52]])

In [14]:
a[a>10]

array([11, 13, 15, 17])

In [16]:
b[b<10]

array([2, 4, 6, 8])